[versions]
com-vanniktech-gradle-maven-publish-plugin = "0.36.0"
kotlin = "2.3.21"
typeflows = "0.32.0-beta"
version-catalog-update = "1.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
typeflows = { id = "io.typeflows", version.ref = "typeflows" }
vannitech = { id = "com.vanniktech.maven.publish", version.ref = "com-vanniktech-gradle-maven-publish-plugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }

[libraries]
typeflows-github = { module = "io.typeflows:typeflows-github", version.ref = "typeflows" }
typeflows-github-marketplace = { module = "io.typeflows:typeflows-github-marketplace", version.ref = "typeflows" }
