name: Publish Artifacts
on:
  repository_dispatch:
    types:
    - release
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        ref: ${{ github.event.client_payload.tag }}
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
    - name: Publish
      run: ./gradlew publish --no-configuration-cache --info -Psign=true -PreleaseVersion="$RELEASE_VERSION" -PsigningKey="$SIGNING_KEY" -PsigningPassword="$SIGNING_PASSWORD"
      env:
        RELEASE_VERSION: ${{ github.event.client_payload.tag }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      shell: bash
    - name: Build release note
      run: |-
        {
            echo "Changelog:"
            TAG=$(echo "refs/tags/$RELEASE_VERSION" | sed "s/.*tags\///g")
            # Find the line with ### version and get content until next ### or end
            awk "/^### $TAG/{flag=1; next} /^### / && flag{flag=0} flag" CHANGELOG.md | sed '/^$/d'
        } > NOTE.md
      env:
        RELEASE_VERSION: ${{ github.event.client_payload.tag }}
      shell: bash
    - name: Create Release
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
      with:
        tag_name: ${{ github.event.client_payload.tag }}
        release_name: ${{ github.event.client_payload.tag }}
        body_path: NOTE.md
        draft: 'false'
        prerelease: 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}